FROM mysql:latest

# Establecer las variables de entorno para configurar MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=dataBase
ENV MYSQL_PASSWORD=root

# Exponer el puerto 3306 para que la base de datos esté accesible
EXPOSE 3306
